# Generated by Django 4.2.11 on 2024-11-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('purchased', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ShoppingListItem',
                'verbose_name_plural': 'ShoppingListItems',
                'db_table': 'shoppinglistitem',
            },
        ),
    ]
