# Generated by Django 4.2.11 on 2024-11-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('meal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='diet_type',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='users.diettype'),
        ),
    ]
