# Generated by Django 4.2.11 on 2024-11-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_recipe_diet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergies',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
